version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studyrobo-backend
    restart: always
    ports:
      - "8081:8080"   # External 8081 → Internal 8080
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080