version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studyrobo-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # fallback if .env missing
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000